name: Build APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'App building type'
        required: true
        default: 'debug'
        type: choice
        options:
        - release
        - debug
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  debug:
    name: Generate Debug APK
    if: ${{ (inputs.buildType == 'debug') || (github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          
      - name: Build
        run: ./gradlew assembleDebug
          
      - name: Store generated APK file
        uses: actions/upload-artifact@v4
        with:
          name: xposed-adblocker
          path: ./app/build/outputs/apk/debug/app-debug.apk
        
      - name: Upload APK file to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Debug Build"
          files: ./app/build/outputs/apk/debug/app-debug.apk
          # gh release upload ${{github.event.release.tag_name}} ./app/build/outputs/apk/debug/app-debug.apk
          
  release:
    name: Generate Release APK
    if: ${{ (inputs.buildType == 'release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build
        run: |
          ./gradlew assembleRelease
      - name: Store generated APK file
        uses: actions/upload-artifact@v4
        with:
          name: xposed-adblocker
          path: ./app/build/outputs/apk/release/app-release.apk
